#!/bin/bash

# check Ngrok status
NGROK_API_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:4040/api)
if [ $NGROK_API_STATUS -ne '200' ]; then
    echo "   >>> NGROK is not running, starting it"
    systemctl start ngrok.service
else
    echo "   >>> NGROK is already running, we will not touch it"
fi

# start application
cd "$( cd "$(dirname "$0")" ; pwd -P )"
python3 ##MAIN_SCRIPT_PATH##
# python3 cash_register_closer/main.py